### ISSUE TITLE
Comparison with other parsers

### ISSUE THREAD

**Issue by Keats** [dragostis/pest#16]
As mentioned on Reddit, some comparisons between nom / oak / lalrpop etc in the README would be neat

**Comment by dragostis** [comment]
Will do as I add more features. Thanks for the issue! 😃

**Comment by Keats** [comment]
If i can replace most of the `lexer.rs`, `parser.rs` and `nodes.rs` in https://github.com/Keats/tera/tree/master/src while keeping nice error messages I'll probably have a go soonish, `pest` and `lalrpop` are on the shortlist. 

Quick question, could I get a full AST (by full, I mean something like the one I get with my manual parser like https://github.com/Keats/tera/blob/master/src/parser.rs#L825-L850) from pest?

Let me know when all the necessary features and docs are there and i'll have a go at it.

**Comment by dragostis** [comment]
@Keats Right now, the idea behind error reporting goes like this:

* out of the box you have deepest expected rules (e.g. "expected any, number or float at position 40"); you can use `_` to make rules quiet and `@` to make them atomic (no white-space or comments between); `Input` currently lacks a method to convert a position to lines and columns, but that shouldn't be so hard
* specific rules can be crated to specialized error, then captured with the `process!` macro

In terms of AST (and if you want to also have those specialized errors that you can match with rules), you can use the `process!` macro and have it return a `Result<Node, ParseError>`. `process!` works like a reduction function that you can call recursively. The documentation for it is not yet done, but [this](https://github.com/dragostis/pest/blob/documentation/src/process.rs#L8) is a pretty good start. I'd like to add more specific examples. Another example for `process!` is in the [calculator test](https://github.com/dragostis/pest/blob/master/tests/calculator.rs#L32).

**Comment by dragostis** [comment]
@Keats By the way, I'm really excited at the proespect of pest being used in production. I'm planning to release `0.2.0` once documentation is on par with the rest of the project with:

* thousandfold performance improvement compared to `0.1.0`; roughly 2-3x parsing speed over Bison (will provide comprehensive benchmarks before the release)
* quiet and atomic rules
* white-space and comment default rules
* token processing
* precedence climbing rule
* lots of bugs solved and tests added

I'd like to try and help if you decide to add pest to tera. Please leave the PR or branch here.

**Comment by dragostis** [comment]
@Keats I've updated the project with more documentation and an updated `README`. The documentation is still not there yet for a `0.2.0` release, but it's definitely serviceable.
