### ISSUE TITLE
Add examples for process!

### ISSUE THREAD

**Issue by Keats** [dragostis/pest#44]
The calculator does the math but I assume most users will want to build an AST so an example for that would be nice, the one in the docs is a bit too light imo.

The Lua language one would be nice but might be quite complex to do, right now the docs seems a bit small for the `process!` part. We could actually put Tera there as an example once it's done.

**Comment by dragostis** [comment]
That would be a great idea! Right now I'm working on a second example for a sentence, word, letter grammar with a simple AST that will probably work well with the other example at explaining how things work.

**Comment by Keats** [comment]
Just to give more context, those are the current nodes in Tera https://github.com/Keats/tera/blob/master/src/nodes.rs#L9-L24, some might change when moving to pest but not that much

**Comment by dragostis** [comment]
I'm going to change something pretty significant:

```
process! {
    main(&self) -> Node {
        // @rec - recursive call on main
        // @<secondary>rec - call secondary
    }

    secondary(&self) -> Node {
        // @rec - recursive call on secondary
        // @<main>rec - call main
    }
}
```

`process!` will now have separate calls that will make everything much easier.

**Comment by Keats** [comment]
I'm not sure what you mean by secondary there

**Comment by dragostis** [comment]
Just a secondary peocessint rule. You'll see after I add the example.
