### ISSUE TITLE
List parsing

### ISSUE THREAD

**Issue by Pyriphlegethon** [dragostis/pest#49]
I have the following rule in my grammar:

```rust
function = { symbol ~ ["("] ~ expression ~ ([","] ~ expression) ~ [")"] }
```
and I try to parse it like this:
```rust
(_: function, fun: main(), arguments: _arguments()) => {
    Function(fun, arguments)
},
```
```rust
_arguments(&self) -> Vec<Expression> {
    (head: main(), tail: _arguments()) => {
        let mut tail = tail;
        tail.push(head);
        tail
    },
    () => {
        Vec::new()
    }
}
```
This however ```panics!``` with the message that no rules matched.
What am I doing wrong?

**Comment by dragostis** [comment]
Can you please provide the whole example with the relevant grammar rule and the whole `process!` call?

**Comment by dragostis** [comment]
Let's suppose you're matching `function symbol expression ...`. If you match `_: function` then call `main()`, `main` will try to match another `_: function`, but the next `Token` in the stream is a `symbol`, so it fails to match. You need to handle `symbol` in `main` if you want this to work.

**Comment by Pyriphlegethon** [comment]
Oh, i accidentally deleted them. This grammar also doesn't work though:
```
impl_rdp! {
    grammar! {
        expression = _{
            function | number | symbol
        }
        number = @{ ["-"]? ~ (["0"] | ['1'..'9'] ~ ['0'..'9']*) }
        symbol = @{ (['a'..'z'] ~ ['a'..'z']*) }
        function = { symbol ~ ["("] ~ expression ~ ([","] ~ expression) ~ [")"] }

        whitespace = _{ [" "] | ["\n"] | ["\r"] | ["\t"] }
    }

    process! {
        main(&self) -> Expression {
            (_: function, fun: main(), arguments: _arguments()) => {
                Expression::Function(Box::new(fun), arguments)
            },    
            (&number: number) => {
                Expression::Integer(number.parse::<i64>().unwrap())
            },
            (&symbol: symbol) => {
                Expression::Symbol(symbol.to_string())
            },
        }
        _arguments(&self) -> Vec<Expression> {
            (head: main(), tail: _arguments()) => {
                let mut tail = tail;
                tail.push(head);
                tail
            },
            () => {
                Vec::new()
            }
        }
    }
}
```

**Comment by dragostis** [comment]
The grammar might need function to be defined so:

```
function = { symbol ~ ["("] ~ expression ~ ([","] ~ expression)* ~ [")"] } // added missing *
```

The problem you're having here is also mentioned in Rust's warning: `warning: function cannot return without recurring, #[warn(unconditional_recursion)] on by default` This happens because `_arguments()` will always call `main()` and then recurse in `_arguments()`. For the recursion to work, you need some kind of condition: you may want to add something before `head`. Right now, after you're matching all `expression`s inside the `function`'s parens, you still call `main()` which doesn't know how to handle the empty case. You could handle this by making `expression` non-silent and catching it in `_arguments`:

```
(_: expression, head: main(), tail: _arguments())
```

**Comment by Pyriphlegethon** [comment]
This still gives me ```no rules matched```:
```rust
impl_rdp! {
    grammar! {
        expression = {
            function | number | symbol
        }
        number = @{ ["-"]? ~ (["0"] | ['1'..'9'] ~ ['0'..'9']*) }
        symbol = @{ (['a'..'z'] ~ ['a'..'z']*) }
        function = { symbol ~ ["("] ~ expression ~ ([","] ~ expression)* ~ [")"] }

        whitespace = _{ [" "] | ["\n"] | ["\r"] | ["\t"] }
    }

    process! {
        main(&self) -> Expression {
            (_: function, fun: main(), arguments: _arguments()) => {
                Expression::Function(Box::new(fun), arguments)
            },    
            (_: expression, &number: number) => {
                Expression::Integer(number.parse::<i64>().unwrap())
            },
            (_: expression, &symbol: symbol) => {
                Expression::Symbol(symbol.to_string())
            },
        }
        _arguments(&self) -> Vec<Expression> {
            (_: expression, head: main(), tail: _arguments()) => {
                let mut tail = tail;
                tail.push(head);
                tail
            },
            () => {
                Vec::new()
            }
        }
    }
}
```

**Comment by dragostis** [comment]
It does because you're matching `_: expression` both in `_arguments` and `main`, but you don't have two `expression` `Token`s, you only have one. You could solve with by making an `argument` rule that accepts an `expression`. Then every argument would be `argument, expression, ...`, so you could first match `_: argument` in `_arguments` then `_: expression` in `main`. Still, you might not need the `expression` `Token` in this case.

**Comment by Pyriphlegethon** [comment]
Like this?
```rust
impl_rdp! {
    grammar! {
        expression = {
            function | number | symbol
        }
		argument = { expression }
        number = @{ ["-"]? ~ (["0"] | ['1'..'9'] ~ ['0'..'9']*) }
        symbol = @{ (['a'..'z'] ~ ['a'..'z']*) }
        function = { symbol ~ ["("] ~ argument ~ ([","] ~ argument)* ~ [")"] }

        whitespace = _{ [" "] | ["\n"] | ["\r"] | ["\t"] }
    }

    process! {
        main(&self) -> Expression {
            (_: function, fun: main(), arguments: _arguments()) => {
                Expression::Function(Box::new(fun), arguments)
            },    
            (_: expression, &number: number) => {
                Expression::Integer(number.parse::<i64>().unwrap())
            },
            (_: expression, &symbol: symbol) => {
                Expression::Symbol(symbol.to_string())
            },
        }
        _arguments(&self) -> Vec<Expression> {
            (_: argument, head: main(), tail: _arguments()) => {
                let mut tail = tail;
                tail.push(head);
                tail
            },
            () => {
                Vec::new()
            }
        }
    }
}```

**Comment by dragostis** [comment]
Sure. You can also make `expression` silent. When trying to debug this, it may be easier to see exactly what `Token`s the parser produces with something like `println!("{:?}", parser.queue())`.

**Comment by Pyriphlegethon** [comment]
Now it works as intended. Thanks.

**Comment by myfreeweb** [comment]
Just encountered this issue as well. Looks like the key is adding a separate `argument = { expression }` rule and matching it in `_arguments`, making `expression` non-silent is not always necessary. This should probably be documented in the crate itself…

**Comment by myfreeweb** [comment]
Looks like this tail recursive process thing does not work for nested lists! The inner list eats up everything on the right, e.g. `[1 [2 3] 4]` gets processed as `[1 [2 3 4]]` instead :(

**Comment by dragostis** [comment]
@myfreeweb This should be possible if you have a `Token` for the end of the list marker (`]`). This won't be necessary in pest 1.0 that I'm currently working on on the `procedural` branch.
