### ISSUE TITLE
Silent atomic rule?

### ISSUE THREAD

**Issue by sunng87** [dragostis/pest#58]
It seems `@_{ ... }` or `_@{ ... }` is not allowed, but I guess it's necessary for some scenario.

**Comment by dragostis** [comment]
The reason I didn't create such a rule was because to me it makes sense that every rule that's supposed to be atomic is important enough to appear in the `Token` queue and also be error reported. But this is something that could be added. 👍 I prefer the `_@{ ... }` syntax.

**Comment by dragostis** [comment]
I'm still not convinced about adding this. This can be achieved like this:

```
...
some_atomic = @{ a ~ whitespace? ~ b }
b = _ { ... }
```

**Comment by sunng87** [comment]
Yes this is not a required feature and can be done via some workaround.
Feel free to close if this adds complexity, or for any other reason.

**Comment by dragostis** [comment]
I'll close this for now as, to me, it adds some unnecessary complexity.
