### ISSUE TITLE
Clippy warnings in expanded grammar

### ISSUE THREAD

**Issue by Keats** [dragostis/pest#65]
I couldn't reproduce it on pest tests but on Tera I get lots of:

```
<pest macros>:70:47: 70:73 note: in this expansion of grammar! (defined in <pest macros>)
src/parser2.rs:32:1: 221:2 note: in this expansion of impl_rdp! (defined in <pest macros>)
<pest macros>:133:9: 139:76 help: 
<pest macros>:133:9: 139:76 help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#block_in_if_condition_stmt
<pest macros>:133:9: 139:76 warning: in an 'if' condition, avoid complex blocks or closures with blocks; instead, move the block or closure higher and bind it with a 'let', #[warn(block_in_if_condition_stmt)] on by default
<pest macros>:133 false , | $ slf | {
```

which seems to come from https://github.com/dragostis/pest/blob/master/src/grammar.rs#L285 and https://github.com/dragostis/pest/blob/master/src/grammar.rs#L309

**Comment by dragostis** [comment]
This warning is not really relevant. The `grammar!` macro generates code that does not have to be particularly readable, it just has to be optimized. This warning is raised because I'm doing an `if { *some complicated condition* } { *code* }`. There's probably a way to stop this warning from showing up, right?

**Comment by dragostis** [comment]
I think you can use `#![cfg_attr(feature = "clippy", allow(block_in_if_condition_stmt))]` if you're using cargo-clippy.

**Comment by Keats** [comment]
I can silence it yes, I was just wondering if it was relevant or not to fix.

**Comment by dragostis** [comment]
Thanks for the report! 😄
